-- Setec · Pilotage des projets — Supabase schema (task model)
-- Run in the Supabase SQL editor before seeding. Idempotent: safe to re-run on
-- an existing database (the "upgrade" section brings older installs in line).
--
-- Access model
--   • Sign-ups are closed: the app calls signInWithOtp with shouldCreateUser=false,
--     and you should also disable "Allow new users to sign up" in
--     Authentication → Providers → Email. Invite users from the dashboard.
--   • Being signed in is NOT enough. A user only sees data once they have a row
--     in `app_users` (see "Granting access" at the bottom). Every policy checks
--     `is_app_user()`, so a stray auth account gets nothing, even via PostgREST.
--   • Deleting projects is reserved to admins; comments can only be edited or
--     deleted by their author (or an admin).

-- ---------------------------------------------------------------- tables

create table if not exists team_members (
  -- "by default" so the seed can keep the sample ids; new members get the next
  -- value from the sequence (no client-side max+1, no id reuse after a delete).
  id           int  generated by default as identity primary key,
  name         text not null check (char_length(name) between 1 and 80),
  initials     text not null check (char_length(initials) between 1 and 4),
  color        text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  role         text not null check (char_length(role) <= 80),
  cost_per_day int  not null default 0 check (cost_per_day >= 0)   -- €/working day, drives EVM
);

create table if not exists projects (
  id             bigint generated always as identity primary key,
  name           text not null check (char_length(name) between 1 and 200),
  client         text not null default 'À définir' check (char_length(client) <= 200),
  discipline     text not null default 'À définir' check (char_length(discipline) <= 120),
  responsable_id int  not null references team_members(id),
  phase_index    int  not null default 0 check (phase_index between 0 and 6),
  status         text not null default 'à jour'
                   check (status in ('à jour', 'à risque', 'en retard', 'terminé')),
  budget         int  not null default 0 check (budget >= 0),   -- fees / honoraires, in k€
  start          date not null,
  deadline       date not null,
  created_at     timestamptz not null default now(),
  constraint projects_dates_ordered check (deadline >= start)
);

-- Editable tasks (sous-tâches). Progress + next deliverable are derived from these.
create table if not exists subtasks (
  id           bigint generated always as identity primary key,
  project_id   bigint  not null references projects(id) on delete cascade,
  name         text    not null check (char_length(name) between 1 and 200),
  assignee_id  int     not null references team_members(id),
  start        date    not null,
  planned_days int     not null default 1 check (planned_days between 1 and 1000),
  done         boolean not null default false,
  -- Predecessor task ids (Finish-to-Start dependencies), same project.
  depends_on   bigint[] not null default '{}'
);

create table if not exists comments (
  id         bigint generated always as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  -- Who wrote it. Defaults to the caller and is enforced by the insert policy,
  -- so a client can't post under someone else's name.
  author_id  uuid   default auth.uid() references auth.users(id) on delete set null,
  -- Display snapshot of the author at posting time.
  author     text   not null,
  initials   text   not null,
  color      text   not null,
  text       text   not null check (char_length(text) between 1 and 5000),
  when_label text,
  created_at timestamptz not null default now()
);

-- Maps a Supabase Auth user to the app: grants access and links the login to a
-- team member (their name/initials/colour are used for comments and the UI).
create table if not exists app_users (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  member_id  int  references team_members(id) on delete set null,
  role       text not null default 'member' check (role in ('member', 'admin')),
  created_at timestamptz not null default now()
);

create index if not exists idx_subtasks_project on subtasks (project_id, start);
create index if not exists idx_subtasks_assignee on subtasks (assignee_id);
create index if not exists idx_comments_project on comments (project_id, created_at);

-- ---------------------------------------------------------------- upgrade
-- Brings databases created from an older version of this file up to date.
-- Constraints are added NOT VALID so existing rows don't block the upgrade.

alter table comments add column if not exists author_id uuid default auth.uid()
  references auth.users(id) on delete set null;
alter table comments alter column when_label drop not null;
alter table subtasks alter column depends_on type bigint[];

do $$
begin
  -- team_members.id: plain int → identity (sequence starts after the max id).
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'team_members' and column_name = 'id' and is_identity = 'YES'
  ) then
    alter table team_members alter column id add generated by default as identity;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'projects_dates_ordered') then
    alter table projects add constraint projects_dates_ordered check (deadline >= start) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'projects_budget_nonneg') then
    alter table projects add constraint projects_budget_nonneg check (budget >= 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_text_len') then
    alter table comments add constraint comments_text_len
      check (char_length(text) between 1 and 5000) not valid;
  end if;
end $$;

-- Realign the team_members sequence with explicit ids (seed inserts them).
-- Callable only with the service-role key (see grants below).
create or replace function sync_team_members_id_seq() returns void
language sql security definer set search_path = public as $$
  select setval(
    pg_get_serial_sequence('team_members', 'id'),
    greatest((select coalesce(max(id), 0) from team_members), 1)
  );
$$;
revoke all on function sync_team_members_id_seq() from public, anon, authenticated;

select sync_team_members_id_seq();

-- ---------------------------------------------------------------- access helpers

create or replace function is_app_user() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from app_users where user_id = auth.uid());
$$;

create or replace function is_app_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from app_users where user_id = auth.uid() and role = 'admin');
$$;

revoke all on function is_app_user()  from public, anon;
revoke all on function is_app_admin() from public, anon;
grant execute on function is_app_user()  to authenticated;
grant execute on function is_app_admin() to authenticated;

-- ---------------------------------------------------------------- RLS

alter table team_members enable row level security;
alter table projects     enable row level security;
alter table subtasks     enable row level security;
alter table comments     enable row level security;
alter table app_users    enable row level security;

-- Drop every policy on our tables (including the old permissive
-- "authenticated read/write" ones) so re-running converges to the set below.
do $$
declare r record;
begin
  for r in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('team_members', 'projects', 'subtasks', 'comments', 'app_users')
  loop
    execute format('drop policy %I on %I', r.policyname, r.tablename);
  end loop;
end $$;

-- team_members / subtasks: any app user can read and edit.
create policy "app users read"  on team_members for select to authenticated using (is_app_user());
create policy "app users write" on team_members for insert to authenticated with check (is_app_user());
create policy "app users edit"  on team_members for update to authenticated using (is_app_user()) with check (is_app_user());
create policy "app users delete" on team_members for delete to authenticated using (is_app_user());

create policy "app users read"  on subtasks for select to authenticated using (is_app_user());
create policy "app users write" on subtasks for insert to authenticated with check (is_app_user());
create policy "app users edit"  on subtasks for update to authenticated using (is_app_user()) with check (is_app_user());
create policy "app users delete" on subtasks for delete to authenticated using (is_app_user());

-- projects: any app user can read/create/edit; only admins can delete.
create policy "app users read"  on projects for select to authenticated using (is_app_user());
create policy "app users write" on projects for insert to authenticated with check (is_app_user());
create policy "app users edit"  on projects for update to authenticated using (is_app_user()) with check (is_app_user());
create policy "admins delete"   on projects for delete to authenticated using (is_app_admin());

-- comments: read for app users; insert only as yourself; edit/delete your own.
create policy "app users read" on comments for select to authenticated using (is_app_user());
create policy "post as self"   on comments for insert to authenticated
  with check (is_app_user() and author_id = auth.uid());
create policy "edit own"       on comments for update to authenticated
  using (is_app_user() and (author_id = auth.uid() or is_app_admin()))
  with check (is_app_user() and (author_id = auth.uid() or is_app_admin()));
create policy "delete own"     on comments for delete to authenticated
  using (is_app_user() and (author_id = auth.uid() or is_app_admin()));

-- app_users: a user can read their own row (the app reads it to know who is
-- signed in); only admins manage access.
create policy "read own"      on app_users for select to authenticated
  using (user_id = auth.uid() or is_app_admin());
create policy "admins manage" on app_users for all to authenticated
  using (is_app_admin()) with check (is_app_admin());

-- ---------------------------------------------------------------- granting access
-- After inviting someone (Authentication → Users → Invite), link them to a team
-- member. The first admin must be created here with the SQL editor:
--
--   insert into app_users (user_id, member_id, role)
--   select id, 1, 'admin' from auth.users where email = 'you@setec.fr';
